<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasterSIRSTempatTidurJenisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
    		[
    			'nama' => 'Penyakit Dalam',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Kesehatan Anak',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Obstetri',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Genekologi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Bedah',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Bedah Orthopedi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Bedah Saraf',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Luka Bakar',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Saraf',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Jiwa',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Psikologi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Penatalaksana pengguna NAPZA',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'THT',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'MATA',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Kulit & Kelamin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Kardiologi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Paru-paru',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Geriatri',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Radioterapi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Kedokteran Nuklir',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Kusta',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Rehabilitasi Medik',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Isolasi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'ICU',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'ICCU',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'NICU/PICU',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Umum',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Gigi & Mulut',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Pelayanan Rawat Darurat',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Perinatologi/Bayi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    	];

    	foreach ($data as $key => $value) {
	        DB::connection('mysql')
	        	->table('master_sirs_tempat_tidur_jenis')
	        	->insert($value);
    	}

        $data = [
    		[
    			'nama' => 'Elektro Kardiographi (EKG)',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Elektro Myographi (EMG)',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Echo Cardiographi (ECG)',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Topometri',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Endoskopi (semua bentuk)',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Hemodialisa',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Densometri Tulang',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Pungsi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Akupuntur',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Hiperbarik',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Herbal / jamu',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Spirometri',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Tes Kulit/Alergi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    	];

        foreach ($data as $key => $value) {
	        DB::connection('mysql')
	        	->table('master_sirs_pelayanan_khusus')
	        	->insert($value);
    	}

		$data = [
    		[
    			'nama' => 'Psikotes',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Rehabilitasi Medik Psikiatrik',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Psikoterapi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Play Therapy',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Terapi Medikamentosa',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Elektro Medik',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Konsult',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    	];

        foreach ($data as $key => $value) {
	        DB::connection('mysql')
	        	->table('master_sirs_kesehatan_jiwa')
	        	->insert($value);
    	}

		$data = [
    		[
    			'nama' => 'Penyakit Dalam',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'BEDAH',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Kesehatan Anak',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Paru-Paru',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Radiologi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'T H T',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Keluarga Berencana',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
    			'nama' => 'SARAF',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
    			'nama' => 'Gigi & Mulut',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
    			'nama' => 'JIWA',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
    			'nama' => 'Kulit & Kelamin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
    			'nama' => 'Mata',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
    			'nama' => 'Spesialisasi Lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
    			'nama' => 'Obsterik & Ginekologi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    	];

        foreach ($data as $key => $value) {
	        DB::connection('mysql')
	        	->table('master_sirs_spesialisasi_rujukan')
	        	->insert($value);
    	}

		$data = [
    		[
				'nomor' => '1',
    			'nama' => 'Membayar Sendiri',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2',
    			'nama' => 'Asuransi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1',
    			'nama' => 'Asuransi Pemerintah',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.2',
    			'nama' => 'Asuransi Swasta',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3',
    			'nama' => 'Keringanan (Cost Sharing)',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '4',
    			'nama' => 'Gratis',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '4.1',
    			'nama' => 'Kartu Sehat',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '4.2',
    			'nama' => 'Keterangan Tidak Mampu',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '4.3',
    			'nama' => 'Lain-Lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    	];

        foreach ($data as $key => $value) {
	        DB::connection('mysql')
	        	->table('master_sirs_cara_bayar')
	        	->insert($value);
    	}

		$data = [
    		[
				'nama' => 'Atas persetujuan dokter',
				'kode' => '1',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Dirujuk',
				'kode' => '2',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Atas permintaan sendiri',
				'kode' => '3',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Meninggal',
				'kode' => '4',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Lainnya',
				'kode' => '5',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    	];

        foreach ($data as $key => $value) {
	        DB::connection('mysql')
	        	->table('master_cara_pulang_inacbg')
	        	->insert($value);
    	}

		$data = [
    		[
				'nama' => 'Selesai Pelayanan',
				'slug' => 'selesai-pelayanan',
				'cara_pulang_inacbg_id' => 1,
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'APS',
				'slug' => 'aps',
				'cara_pulang_inacbg_id' => 3,
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Dirujuk',
				'slug' => 'rujuk',
				'cara_pulang_inacbg_id' => 2,
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Meninggal',
				'slug' => 'meninggal',
				'cara_pulang_inacbg_id' => 4,
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Lain - Lain',
				'slug' => 'lainnya',
				'cara_pulang_inacbg_id' => 5,
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Batal',
				'slug' => 'batal',
				'cara_pulang_inacbg_id' => NULL,
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    	];

        foreach ($data as $key => $value) {
	        DB::connection('mysql')
	        	->table('master_cara_pulang')
	        	->insert($value);
    	}

		$data = [
    		[
				'nama' => 'Sembuh',
				'slug' => 'sembuh',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Membaik',
				'slug' => 'membaik',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Meninggal',
				'slug' => 'meninggal',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Sakit',
				'slug' => 'sakit',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    	];

        foreach ($data as $key => $value) {
	        DB::connection('mysql')
	        	->table('master_status_pulang')
	        	->insert($value);
    	}

		$data = [
    		[
				'nomor' => '1',
    			'nama' => 'Tumpatan Gigi Tetap',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2',
    			'nama' => 'Tumpatan Gigi Sulung',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3',
    			'nama' => 'Pengobatan Pulpa',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '4',
    			'nama' => 'Pencabutan Gigi Tetap',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '5',
    			'nama' => 'Pencabutan Gigi Sulung',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '6',
    			'nama' => 'Pengobatan Periodontal',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '7',
    			'nama' => 'Pengobatan Abses',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '8',
    			'nama' => 'Pembersihan Karang Gigi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '9',
    			'nama' => 'Prothese Lengkap',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '10',
    			'nama' => 'Prothese Sebagian',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '11',
    			'nama' => 'Prothese Cekat',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '12',
    			'nama' => 'Orthodonti',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '13',
    			'nama' => 'Jacket/Bridge',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '14',
    			'nama' => 'Bedah Mulut',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    	];

        foreach ($data as $key => $value) {
	        DB::connection('mysql')
	        	->table('master_sirs_gigi_mulut')
	        	->insert($value);
    	}

		$data = [
    		[
				'nomor' => '1',
    			'nama' => 'Persalinan Normal',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2',
    			'nama' => 'Sectio caesaria',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3',
    			'nama' => 'Pers dg komplikasi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.1',
    			'nama' => 'Perd sbl Persalinan',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.2',
    			'nama' => 'Perd sdh Persalinan',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.3',
    			'nama' => 'Pre Eclampsi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.4',
    			'nama' => 'Eclampsi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.5',
    			'nama' => 'Infeksi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.6',
    			'nama' => 'Lain - Lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '4',
    			'nama' => 'Abortus',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '5.1',
    			'nama' => 'Imunisasi - TT1',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '5.2',
    			'nama' => 'Imunisasi - TT2',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    	];

        foreach ($data as $key => $value) {
	        DB::connection('mysql')
	        	->table('master_sirs_kegiatan_kebidanan')
	        	->insert($value);
    	}

		$data = [
    		[
				'nomor' => '1',
    			'nama' => 'Bayi Lahir Hidup',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.1',
    			'nama' => '>= 2500 gram',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.2',
    			'nama' => '< 2500 gram',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2',
    			'nama' => 'Kematian Perinatal',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1',
    			'nama' => 'Kelahiran Mati',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.2',
    			'nama' => 'Mati Neonatal < 7 Hari',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3',
    			'nama' => 'Sebab Kematian',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.1',
    			'nama' => 'Asphyxia',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.2',
    			'nama' => 'Trauma Kelahiran',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.3',
    			'nama' => 'BBLR',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.4',
    			'nama' => 'Tetanus Neonatorum',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.5',
    			'nama' => 'Kelainan Congenital',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.6',
    			'nama' => 'ISPA',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.7',
    			'nama' => 'Diare',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.8',
    			'nama' => 'Lain - Lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    	];

        foreach ($data as $key => $value) {
	        DB::connection('mysql')
	        	->table('master_sirs_kegiatan_perinatologi')
	        	->insert($value);
    	}

		$data = [
    		[
    			'nama' => 'Bedah',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Obstetrik & Ginekologi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Bedah Saraf',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'T H T',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Mata',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Kulit & Kelamin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Gigi & Mulut',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    		[
    			'nama' => 'Bedah Anak',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Kardiovaskuler',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Bedah Orthopedi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Thorak',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Digestive',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Urologi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
            [
    			'nama' => 'Lain-Lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    	];

    	foreach ($data as $key => $value) {
	        DB::connection('mysql')
	        	->table('master_sirs_spesialisasi_bedah')
	        	->insert($value);
    	}

		$data = [
    		[
				'nomor' => '1',
    			'nama' => 'RADIODIAGNOSTIK Foto tanpa bahan kontras',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2',
    			'nama' => 'Foto dengan bahan kontras',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3',
    			'nama' => 'Foto dengan rol film',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '4',
    			'nama' => 'Flouroskopi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '5',
    			'nama' => 'Foto Gigi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '6',
    			'nama' => 'C.T. Scan',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '7',
    			'nama' => 'Lymphografi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '8',
    			'nama' => 'Angiograpi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '9',
    			'nama' => 'Lain-Lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.1',
    			'nama' => 'RADIOTHERAPI Jumlah Kegiatan Radiotherapi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.2',
    			'nama' => 'Lain-Lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1',
    			'nama' => 'KEDOKTERAN NUKLIR Jumlah Kegiatan Diagnostik',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.2',
    			'nama' => 'Jumlah Kegiatan Therapi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.3',
    			'nama' => 'Lain-Lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.1',
    			'nama' => 'IMAGING/PENCITRAAN USG',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.2',
    			'nama' => 'MRI',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.3',
    			'nama' => 'Lain-lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    	];

        foreach ($data as $key => $value) {
	        DB::connection('mysql')
	        	->table('master_sirs_kegiatan_radiologi')
	        	->insert($value);
    	}

		$data = [
    		[
				'nomor' => '1',
    			'nama' => 'HEMATOLOGI',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.1',
    			'nama' => 'Sitologi Sel Darah',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.1.1',
    			'nama' => 'Eosinofil, hitung jumlah',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.1.2',
    			'nama' => 'Eritrosit, hitung jumlah',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.1.3',
    			'nama' => 'Leukosit, hitung jenis',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.1.4',
    			'nama' => 'Leukosit, hitung jumlah',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.1.5',
    			'nama' => 'Limfosit plasma biru, hitung jumlah',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.1.6',
    			'nama' => 'Morfologi sel',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.1.7',
    			'nama' => 'Retikulosit, hitung jumlah',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.1.8',
    			'nama' => 'Trombosit, hitung jumlah',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.2',
    			'nama' => 'Sitokimia darah',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.2.1',
    			'nama' => 'Besi, pewarnaan',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.2.2',
    			'nama' => 'Neutrophil Alkaline Phosphatase/NAP, pewarnaan',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.2.3',
    			'nama' => 'Nitroblue tetrazoleum, pewarnaan',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.2.4',
    			'nama' => 'Periodic Acid Schiff/PAS, pewarnaan',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.2.5',
    			'nama' => 'Peroksidase, pewarnaan',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.2.6',
    			'nama' => 'Sudan Black B, pewarnaan',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.3',
    			'nama' => 'Analisa Hb',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.3.1',
    			'nama' => 'Hemoglobin A2, penetapan kadar',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.3.2',
    			'nama' => 'Hemoglobin F, identifikasi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.3.3',
    			'nama' => 'Hemoglobin F, penetapan kadar',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.4',
    			'nama' => 'Perbankan Darah',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.4.1',
    			'nama' => 'Coomb`s, percob. direk, indirek',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.4.2',
    			'nama' => 'Penetapan gol darah A, B, O, Rh dll',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.4.3',
    			'nama' => 'Uji saring antibodi pada darah donor',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.4.4',
    			'nama' => 'Uji silang mayor/minor',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5',
    			'nama' => 'Hemostasis',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.1',
    			'nama' => 'Agregasi trombosit',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.2',
    			'nama' => 'Antitrombin III',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.3',
    			'nama' => 'Cryofibrinogen/cryoglobulin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.4',
    			'nama' => 'D Dimer',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.5',
    			'nama' => 'Euglobulin Clotlysis',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.6',
    			'nama' => 'Faktor pembekuan V, VII, VIII, IX, X',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.7',
    			'nama' => 'Faktor pembekuan VIII, IX, X, penetapan kadar',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.8',
    			'nama' => 'Faktor pembekuan XII, XIII, penetapan kadar',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.9',
    			'nama' => 'Fibrinogen Degradation Product/FDP',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.10',
    			'nama' => 'Fibrinogen, penetapan kadar',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.11',
    			'nama' => 'Pembekuan, masa',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.12',
    			'nama' => 'Pembendungan, percobaan',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.13',
    			'nama' => 'Perdarahan, masa',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.14',
    			'nama' => 'Plasminogen activator inhibitor -1/PAI-1',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.15',
    			'nama' => 'Protein C',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.16',
    			'nama' => 'Protein S',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.17',
    			'nama' => 'Protrombin plasma, masa',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.18',
    			'nama' => 'Retraksi bekuan',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.19',
    			'nama' => 'Trombin, masa',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.20',
    			'nama' => 'Trombin, penetapan waktu seri',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.21',
    			'nama' => 'Tromboplastin, masa partial teraktivasi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5.22',
    			'nama' => 'Trombotest/Owren Test',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.6',
    			'nama' => 'Pemeriksaan lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.6.1',
    			'nama' => 'Eritrosit, ketahanan osmotik',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.6.2',
    			'nama' => 'Ham`s test',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.6.3',
    			'nama' => 'Hematokrit, penetapan nilai',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.6.4',
    			'nama' => 'Hemoglobin Eritrosit Rata-rata/HER',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.6.5',
    			'nama' => 'Konsentrasi Hemoglobin Eritrosit Rata-rata/KHER',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.6.6',
    			'nama' => 'Laju endapan darah',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.6.7',
    			'nama' => 'Sel L.E.',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.6.8',
    			'nama' => 'Volume Eritrosit Rata-rata/VER',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2',
    			'nama' => 'KIMIA KLINIK',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1',
    			'nama' => 'Protein dan NPN',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.1',
    			'nama' => 'Albumin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.3',
    			'nama' => 'Asam urat',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.4',
    			'nama' => 'Bilirubin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.5',
    			'nama' => 'Gamma globulin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.6',
    			'nama' => 'Globulin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.6',
    			'nama' => 'Globulin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.7',
    			'nama' => 'Haptoglobin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.8',
    			'nama' => 'Kreatinin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.9',
    			'nama' => 'Methemoglobin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.10',
    			'nama' => 'Mikroalbumin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.11',
    			'nama' => 'Myoglobin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.12',
    			'nama' => 'Porfirin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.13',
    			'nama' => 'Protein Bence Jones',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.14',
    			'nama' => 'Protein Elektroforesis',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.15',
    			'nama' => 'Protein Esbach',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.16',
    			'nama' => 'Protein, penetapan kualitatif',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.17',
    			'nama' => 'Protein, penetapan semikuantitatif',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.18',
    			'nama' => 'Protein Total, penetapan kuantitatif',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.19',
    			'nama' => 'Urea/BUN',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.20',
    			'nama' => 'Urobilin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1.21',
    			'nama' => 'Urobilinogen',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.2',
    			'nama' => 'Karbohidrat',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.2.1',
    			'nama' => 'Amilum',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.2.2',
    			'nama' => 'Fruktosa',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.2.3',
    			'nama' => 'Galaktosa',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.2.4',
    			'nama' => 'Glukosa',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.2.5',
    			'nama' => 'Laktosa',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.3',
    			'nama' => 'Lipid, Lipoprotein, Apoprotein',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.3.1',
    			'nama' => 'Apoprotein A/B',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.3.2',
    			'nama' => 'Fosfolipid/serebrosit/sfingolipid',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.3.3',
    			'nama' => 'Kolesterol High Density Lipoprotein (HDL)',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.3.4',
    			'nama' => 'Kolesterol Low Density Lipoprotein (LDL)',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.3.5',
    			'nama' => 'Kolesterol total',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.3.6',
    			'nama' => 'Lipid total',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.3.7',
    			'nama' => 'Lipoprotein (a) / Lp (a)',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.3.8',
    			'nama' => 'Small Dense LDL',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.3.3',
    			'nama' => 'Kolesterol High Density Lipoprotein (HDL)',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.3.9',
    			'nama' => 'Trigliserida',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.4',
    			'nama' => 'Enzim',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.4.1',
    			'nama' => 'Alkali fosfatase',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.4.2',
    			'nama' => 'Aldolase/ALD',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.4.3',
    			'nama' => 'Amilase',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.4.4',
    			'nama' => 'Asam fosfatase',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.4.5',
    			'nama' => 'Cholinesterase',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.4.6',
    			'nama' => 'Creatinin, Kinase, MB Iso enzym',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.4.7',
    			'nama' => 'Creatinin, Phosphokinase CPK-NAC = Creatinin Kinas',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.4.8',
    			'nama' => 'Gamma GT/Glutamil Transferase',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.4.9',
    			'nama' => 'Glutamat Lakto Dehidrogenase/GLDH',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.4.10',
    			'nama' => 'Glutamat Oksaloasetik Transaminase/GOT=Aspartat Am',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.4.11',
    			'nama' => 'Glutamat Piruvat Transaminase/GPT = Alanin Amino T',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.4.12',
    			'nama' => 'Hidroksi Butirik Dehidrogenase/HBDH',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.4.13',
    			'nama' => 'Isositrat Dehidrogenase/ICD',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.4.14',
    			'nama' => 'Laktat Dehidrogenase/LDH',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.4.15',
    			'nama' => 'Leucine Amino Peptidase/LAP',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.4.16',
    			'nama' => 'Lipase',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5',
    			'nama' => 'Mikronutrient dan Monitoring kadar terapi obat',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.1',
    			'nama' => 'Aminofilin/Teofilin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.2',
    			'nama' => 'Asam folat',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.3',
    			'nama' => 'Besi, penetapan kadar',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.4',
    			'nama' => 'Besi - TIBC',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.5',
    			'nama' => 'Besi, unsaturated IBC',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.6',
    			'nama' => 'Digitoksin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.7',
    			'nama' => 'Digoksin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.8',
    			'nama' => 'Fenitoin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.9',
    			'nama' => 'Fenobarbital',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.10',
    			'nama' => 'Ferritin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.11',
    			'nama' => 'Iodium',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.12',
    			'nama' => 'Isoniazid',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.13',
    			'nama' => 'Karbamazepin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.14',
    			'nama' => 'Magnesium',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.15',
    			'nama' => 'Metotreksat',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.16',
    			'nama' => 'Propanolol',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.17',
    			'nama' => 'Seng',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.18',
    			'nama' => 'Siklosporin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.19',
    			'nama' => 'Tembaga',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.20',
    			'nama' => 'Vitamin A',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5.21',
    			'nama' => 'Vitamin B12',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.6',
    			'nama' => 'Elektrolit',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.6.1',
    			'nama' => 'Fosfat anorganik',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.6.2',
    			'nama' => 'Kalium',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.6.3',
    			'nama' => 'Kalsium',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.6.4',
    			'nama' => 'Klorida',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.6.5',
    			'nama' => 'Natrium',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.6.6',
    			'nama' => 'Magnesium',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.7',
    			'nama' => 'Fungsi Organ',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.7.1',
    			'nama' => 'Asam laktat',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.7.2',
    			'nama' => 'Creatinin clearance',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.7.3',
    			'nama' => 'Cystatin C',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.7.4',
    			'nama' => 'Indeks ikterus',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.7.5',
    			'nama' => 'Insulin clearance',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.7.6',
    			'nama' => 'Insulin dalam plasma',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.7.7',
    			'nama' => 'Kalsium',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.7.8',
    			'nama' => 'Lemak, tes absorbsi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.7.9',
    			'nama' => 'Urea clearance',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8',
    			'nama' => 'Hormon dan Fungsi Endokrin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.1',
    			'nama' => 'Adenocorticotropin Hormon/ACTH',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.2',
    			'nama' => 'Anti Diuretik Hormon/ADH Respon',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.3',
    			'nama' => 'Aldosteron',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.4',
    			'nama' => 'Calcitonin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.5',
    			'nama' => 'C Peptide',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.6',
    			'nama' => 'Estrogen',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.7',
    			'nama' => 'Estradiol, 17 Beta',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.8',
    			'nama' => 'Follicle Stimulating Hormon',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.9',
    			'nama' => 'Fruktosamin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.10',
    			'nama' => 'Gastrin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.11',
    			'nama' => 'Glucocorticoid',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.12',
    			'nama' => 'Growth Hormon',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.13',
    			'nama' => 'Hb glikosilat/HbA1c',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.14',
    			'nama' => 'Human Chorionic Gonadotropin/HCG',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.15',
    			'nama' => 'Insulin Growth Factor 1 / IGF1',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.16',
    			'nama' => 'Iodine uptake dan saturasi/T3 dan T4 uptake',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.17',
    			'nama' => 'Insulin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.18',
    			'nama' => 'Keton',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.19',
    			'nama' => 'Kortisol',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.20',
    			'nama' => 'Luteinizing Hormon/LH',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.21',
    			'nama' => 'Pankreas, fungsi dengan tes triolen',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.22',
    			'nama' => 'Pregnandiol',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.23',
    			'nama' => 'Progesteron',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.24',
    			'nama' => 'Prolaktin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.25',
    			'nama' => 'Renin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.26',
    			'nama' => 'Testosteron',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.27',
    			'nama' => 'Thyroglobulin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.28',
    			'nama' => 'Thyroxin dalam serum/T4',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.29',
    			'nama' => 'Thyrotropic Release Factor Assay',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.30',
    			'nama' => 'Thyroid Stimulating Hormon/TSH',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],

			[
				'nomor' => '2.8.31',
    			'nama' => 'Thyroid, tes fungsi yang lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.8.32',
    			'nama' => 'Vinyl Mandelic Acid/VMA',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.9',
    			'nama' => 'Pemeriksaan Lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.9.1',
    			'nama' => 'Analisa batu',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.9.2',
    			'nama' => 'Analisa cairan otak',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.9.3',
    			'nama' => 'Analisa cairan sendi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.9.4',
    			'nama' => 'Analisa cairan tubuh',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.9.5',
    			'nama' => 'Analisa sperma:volume, bau, warna, liquefaksi, vis',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.9.6',
    			'nama' => 'Analisa tinja: sel darah, lemak, sisa makanan',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.9.7',
    			'nama' => 'Hemosiderin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.9.8',
    			'nama' => 'Homosistein',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.9.9',
    			'nama' => 'Oval fat bodies',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.9.10',
    			'nama' => 'Sel, hitung jenis',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.9.11',
    			'nama' => 'Sel, hitung jumlah',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.9.12',
    			'nama' => 'Tes kehamilan',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.9.13',
    			'nama' => 'Troponin T/I',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.9.14',
    			'nama' => 'Urinalisis',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    	];

        foreach ($data as $key => $value) {
	        DB::connection('mysql')
	        	->table('master_sirs_kegiatan_lab')
	        	->insert($value);
    	}

		$data = [
    		[
				'nama' => 'Penyakit Dalam',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Bedah',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Kesehatan Anak (Neonatal)',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Kesehatan Anak Lainnya)',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Obstetri & Ginekologi (Ibu Hamil)',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Obstetri & Ginekologi Lainnya)',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Keluarga Berencana',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Bedah Saraf',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Saraf',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Jiwa',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Napza',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Psikologi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'THT',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Mata',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Kulit dan Kelamin',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Gigi & Mulut',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Geriatri',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Kardiologi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Radiologi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Bedah Orthopedi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Paru - Paru',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Kusta',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Umum',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Rawat Darurat',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Rehabilitasi Medik',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Akupungtur Medik',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Konsultasi Gizi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Day Care',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nama' => 'Lain - Lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    	];

        foreach ($data as $key => $value) {
	        DB::connection('mysql')
	        	->table('master_sirs_kunjungan_kegiatan')
	        	->insert($value);
    	}

		$data = [
    		[
				'nomor' => '1',
    			'nama' => 'Medis',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.1',
    			'nama' => 'Gait Analyzer',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.2',
    			'nama' => 'E M G',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.3',
    			'nama' => 'Uro Dinamic',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.4',
    			'nama' => 'Side Back',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.5',
    			'nama' => 'E N Tree',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.6',
    			'nama' => 'Spyrometer',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.7',
    			'nama' => 'Static Bicycle',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.8',
    			'nama' => 'Tread Mill',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.9',
    			'nama' => 'Body Platysmograf',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '1.10',
    			'nama' => 'lain-lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2',
    			'nama' => 'Fisioterapi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.1',
    			'nama' => 'Latihan Fisik',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.2',
    			'nama' => 'Aktinoterapi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.3',
    			'nama' => 'Elektroterapi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.4',
    			'nama' => 'Hidroterapi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.5',
    			'nama' => 'Traksi Lumbal & Cervical',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '2.6',
    			'nama' => 'Lain-Lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3',
    			'nama' => 'Okupasiterapi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.1',
    			'nama' => 'Snoosien Room',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.2',
    			'nama' => 'Sensori Integrasi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.3',
    			'nama' => 'Latihan aktivitas kehidupan sehari-hari',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.4',
    			'nama' => 'Proper Body Mekanik',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.5',
    			'nama' => 'Pembuatan Alat Lontar & Adaptasi Alat',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.6',
    			'nama' => 'Analisa Persiapan Kerja',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.7',
    			'nama' => 'Latihan Relaksasi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.8',
    			'nama' => 'Analisa & Intervensi, Persepsi, Kognitif, Psikomot',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '3.9',
    			'nama' => 'Lain-lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '4',
    			'nama' => 'Terapi Wicara',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '4.1',
    			'nama' => 'Fungsi Bicara',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '4.2',
    			'nama' => 'Fungsi Bahasa / Laku',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '4.3',
    			'nama' => 'Fungsi Menelan',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '4.4',
    			'nama' => 'Lain-lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '5',
    			'nama' => 'Psikologi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '5.1',
    			'nama' => 'Psikolog Anak',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '5.2',
    			'nama' => 'Psikolog Dewasa',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '5.3',
    			'nama' => 'Lain-lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '6',
    			'nama' => 'Sosial Medis',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '6.1',
    			'nama' => 'Evaluasi Lingkungan Rumah',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '6.2',
    			'nama' => 'Evaluasi Ekonomi',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '6.3',
    			'nama' => 'Evaluasi Pekerjaan',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '6.4',
    			'nama' => 'Lain-lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '7',
    			'nama' => 'Ortotik Prostetik',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '7.1',
    			'nama' => 'Pembuatan Alat Bantu',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '7.2',
    			'nama' => 'Pembuatan Alat Anggota Tiruan',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '7.3',
    			'nama' => 'Lain-Lain',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
			[
				'nomor' => '8',
    			'nama' => 'Kunjungan Rumah',
    			'created_at' => date('Y-m-d H:i:s'),
    			'updated_at' => date('Y-m-d H:i:s'),
    			'deleted_at' => NULL,
    		],
    	];

        foreach ($data as $key => $value) {
	        DB::connection('mysql')
	        	->table('master_sirs_rehab_medik')
	        	->insert($value);
    	}
    }
}
