
	$(`:text[name="alasan_masuk"]`).val(item.alasan_masuk);
	$(`:text[name="diagnosa_masuk"]`).val(item.diagnosa_masuk);
	$(`:text[name="diagnosa_keperawatan_saat_mrs"]`).val(item.diagnosa_keperawatan_saat_mrs);
	$(`:text[name="estimasi_lamanya_perawatan_pasien"]`).val(item.estimasi_lamanya_perawatan_pasien);
	$(`:text[name="keadaan_krs"]`).val(item.keadaan_krs);
	$(`:text[name="diagnosa_keluar"]`).val(item.diagnosa_keluar);
	$(`:text[name="diagnosa_keperawatan_saat_krs"]`).val(item.diagnosa_keperawatan_saat_krs);
	$(`:text[name="lama_dirawat"]`).val(item.lama_dirawat);
	$(`:checkbox[name="pemeriksaan_penunjang_laboratorium"]`).prop("checked", item.pemeriksaan_penunjang_laboratorium != null);
	$(`:checkbox[name="pemeriksaan_penunjang_eeg"]`).prop("checked", item.pemeriksaan_penunjang_eeg != null);
	$(`:checkbox[name="pemeriksaan_penunjang_bm"]`).prop("checked", item.pemeriksaan_penunjang_bm != null);
	$(`:checkbox[name="pemeriksaan_penunjang_ekg"]`).prop("checked", item.pemeriksaan_penunjang_ekg != null);
	$(`:checkbox[name="pemeriksaan_penunjang_foto_rontgen"]`).prop("checked", item.pemeriksaan_penunjang_foto_rontgen != null);
	$(`:checkbox[name="pemeriksaan_penunjang_lainnya"]`).prop("checked", item.pemeriksaan_penunjang_lainnya != null);
	$(`:text[name="pemeriksaan_penunjang_lain_lain"]`).val(item.pemeriksaan_penunjang_lain_lain);
	$(`:checkbox[name="pasien_tinggal_dengan_suami_istri"]`).prop("checked", item.pasien_tinggal_dengan_suami_istri != null);
	$(`:checkbox[name="pasien_tinggal_dengan_sendiri"]`).prop("checked", item.pasien_tinggal_dengan_sendiri != null);
	$(`:checkbox[name="pasien_tinggal_dengan_orang_tua"]`).prop("checked", item.pasien_tinggal_dengan_orang_tua != null);
	$(`:checkbox[name="pasien_tinggal_dengan_anak"]`).prop("checked", item.pasien_tinggal_dengan_anak != null);
	$(`:checkbox[name="pasien_tinggal_dengan_keluarga_lain"]`).prop("checked", item.pasien_tinggal_dengan_keluarga_lain != null);
	$(`:checkbox[name="pasien_tinggal_dengan_lainnya"]`).prop("checked", item.pasien_tinggal_dengan_lainnya != null);
	$(`:text[name="pasien_tinggal_dengan_lain_lain"]`).val(item.pasien_tinggal_dengan_lain_lain);
	$(`:text[name="keterangan_lain_lain"]`).val(item.keterangan_lain_lain);
	$(`:checkbox[name="rencana_kegiatan_pasien_saat_pulang_bekerja"]`).prop("checked", item.rencana_kegiatan_pasien_saat_pulang_bekerja != null);
	$(`:checkbox[name="rencana_kegiatan_pasien_saat_pulang_sekolah"]`).prop("checked", item.rencana_kegiatan_pasien_saat_pulang_sekolah != null);
	$(`:checkbox[name="rencana_kegiatan_pasien_saat_pulang_lainnya"]`).prop("checked", item.rencana_kegiatan_pasien_saat_pulang_lainnya != null);
	$(`:text[name="keterangan_pekerjaan"]`).val(item.keterangan_pekerjaan);
	$(`:text[name="keterangan_jenjang_pendidikan"]`).val(item.keterangan_jenjang_pendidikan);
	$(`:text[name="keterangan_kegiatan_lain"]`).val(item.keterangan_kegiatan_lain);
	$(`:checkbox[name="perlu_bantuan_dalam_hal_minum_obat"]`).prop("checked", item.perlu_bantuan_dalam_hal_minum_obat != null);
	$(`:checkbox[name="perlu_bantuan_dalam_hal_mandi"]`).prop("checked", item.perlu_bantuan_dalam_hal_mandi != null);
	$(`:checkbox[name="perlu_bantuan_dalam_hal_makan"]`).prop("checked", item.perlu_bantuan_dalam_hal_makan != null);
	$(`:checkbox[name="perlu_bantuan_dalam_hal_berhias"]`).prop("checked", item.perlu_bantuan_dalam_hal_berhias != null);
	$(`:checkbox[name="perlu_bantuan_dalam_hal_toiletting"]`).prop("checked", item.perlu_bantuan_dalam_hal_toiletting != null);
	$(`:radio[name="alat_medis_yang_digunakan_saat_keluar_rs"][value="${item.alat_medis_yang_digunakan_saat_keluar_rs}"]`).prop("checked", true);
	$(`:text[name="keterangan_alat_medis_yang_digunakan"]`).val(item.keterangan_alat_medis_yang_digunakan);
	$(`:radio[name="alat_bantu_yang_digunakan_saat_keluar_rs"][value="${item.alat_bantu_yang_digunakan_saat_keluar_rs}"]`).prop("checked", true);
	$(`:text[name="keterangan_alat_bantu_yang_digunakan"]`).val(item.keterangan_alat_bantu_yang_digunakan);
	$(`:text[name="skor_resiko_jatuh__saat_krs"]`).val(item.skor_resiko_jatuh__saat_krs);
	$(`:text[name="skor_resiko_nyeri_saat_krs"]`).val(item.skor_resiko_nyeri_saat_krs);
	$(`:radio[name="diet_khusus"][value="${item.diet_khusus}"]`).prop("checked", true);
	$(`:text[name="keterangan_diet_khusus"]`).val(item.keterangan_diet_khusus);
	$(`:text[name="nasehat"]`).val(item.nasehat);