
	$(`:radio[name="saya_tidak_bermasalah_untuk_berjalan_keliling"][value="${item.saya_tidak_bermasalah_untuk_berjalan_keliling}"]`).prop("checked", true);
	$(`:text[name="tanggal_tidak_masalah_berjalan_keliling"]`).val(formatDate(item.tanggal_tidak_masalah_berjalan_keliling));
	$(`:text[name="tanggal_masalah_berjalan_keliling"]`).val(formatDate(item.tanggal_masalah_berjalan_keliling));
	$(`:radio[name="saya_mengalami_masalah_untuk_berjalan_keliling"][value="${item.saya_mengalami_masalah_untuk_berjalan_keliling}"]`).prop("checked", true);
	$(`:text[name="tanggal_terbaring_di_kasur"]`).val(formatDate(item.tanggal_terbaring_di_kasur));
	$(`:radio[name="saya_hanya_terbaring_di_kasur"][value="${item.saya_hanya_terbaring_di_kasur}"]`).prop("checked", true);
	$(`:text[name="tanggal_mengurus_diri_sendiri"]`).val(formatDate(item.tanggal_mengurus_diri_sendiri));
	$(`:radio[name="saya_tidak_bermasalah_mengurus_diri_sendiri"][value="${item.saya_tidak_bermasalah_mengurus_diri_sendiri}"]`).prop("checked", true);
	$(`:text[name="tanggal_bermasalah_membersihkan_pakaian"]`).val(formatDate(item.tanggal_bermasalah_membersihkan_pakaian));
	$(`:radio[name="saya_bermasalah_untuk_membersihkan_dan_memakai_pakaian_sendiri"][value="${item.saya_bermasalah_untuk_membersihkan_dan_memakai_pakaian_sendiri}"]`).prop("checked", true);
	$(`:text[name="tanggal_tidak_mampu_sama_sekali_memakai_pakaian"]`).val(formatDate(item.tanggal_tidak_mampu_sama_sekali_memakai_pakaian));
	$(`:radio[name="saya_tidak_mampu_memakai_pakaian_sendiri"][value="${item.saya_tidak_mampu_memakai_pakaian_sendiri}"]`).prop("checked", true);
	$(`:text[name="tanggal_aktivitas_harian"]`).val(formatDate(item.tanggal_aktivitas_harian));
	$(`:radio[name="saya_tidak_bermasalah_melakukan_aktivitas_harian"][value="${item.saya_tidak_bermasalah_melakukan_aktivitas_harian}"]`).prop("checked", true);
	$(`:text[name="tanggal_bermasalah_aktivitas_harian"]`).val(formatDate(item.tanggal_bermasalah_aktivitas_harian));
	$(`:radio[name="saya_bermasalah_melakukan_aktivitas"][value="${item.saya_bermasalah_melakukan_aktivitas}"]`).prop("checked", true);
	$(`:text[name="tanggal_tidak_dapat_menjalankan_aktivitas"]`).val(formatDate(item.tanggal_tidak_dapat_menjalankan_aktivitas));
	$(`:radio[name="saya_tidak_dapat_menjalankan_aktivitas"][value="${item.saya_tidak_dapat_menjalankan_aktivitas}"]`).prop("checked", true);
	$(`:text[name="tanggal_tidak_punya_keluhan_nyeri"]`).val(formatDate(item.tanggal_tidak_punya_keluhan_nyeri));
	$(`:radio[name="saya_tidak_punya_keluhan_nyeri"][value="${item.saya_tidak_punya_keluhan_nyeri}"]`).prop("checked", true);
	$(`:text[name="tanggal_tidak_punya_keluhan_nyeri_sedang"]`).val(formatDate(item.tanggal_tidak_punya_keluhan_nyeri_sedang));
	$(`:radio[name="saya_tidak_punya_keluhan_nyeri_sedang"][value="${item.saya_tidak_punya_keluhan_nyeri_sedang}"]`).prop("checked", true);
	$(`:text[name="tanggal_tidak_punya_keluhan_nyeri_berat"]`).val(formatDate(item.tanggal_tidak_punya_keluhan_nyeri_berat));
	$(`:radio[name="saya_tidak_punya_keluhan_nyeri_berat"][value="${item.saya_tidak_punya_keluhan_nyeri_berat}"]`).prop("checked", true);
	$(`:text[name="tanggal_tidak_gelisah"]`).val(formatDate(item.tanggal_tidak_gelisah));
	$(`:radio[name="saya_tidak_gelisah_maupun_depresi"][value="${item.saya_tidak_gelisah_maupun_depresi}"]`).prop("checked", true);
	$(`:text[name="tanggal_tidak_gelisah_maupun_depresi_sedang"]`).val(formatDate(item.tanggal_tidak_gelisah_maupun_depresi_sedang));
	$(`:radio[name="saya_mengalami_gelisah_maupun_depresi_sedang"][value="${item.saya_mengalami_gelisah_maupun_depresi_sedang}"]`).prop("checked", true);
	$(`:text[name="tanggal_gelisah_maupun_depresi_berat"]`).val(formatDate(item.tanggal_gelisah_maupun_depresi_berat));
	$(`:radio[name="saya_mengalami_tgelisah_maupun_depresi_berat"][value="${item.saya_mengalami_tgelisah_maupun_depresi_berat}"]`).prop("checked", true);