<table>
	<tr>
		<td>id</td>
		<td>no_rm</td>
		<td>nama</td>
		<td>jenis_kelamin</td>
		<td>jenis_kartu_identitas</td>
		<td>no_identitas</td>
		<td>status_pernikahan</td>
		<td>tempat_lahir</td>
		<td>tgl_lahir</td>
		<td>alamat</td>
		<td>alamat_kota</td>
		<td>alamat_kecamatan</td>
		<td>alamat_kelurahan</td>
		<td>no_telp</td>
		<td>pekerjaan</td>
		<td>agama</td>
		<td>pendidikan</td>
		<td>bahasa</td>
		<td>suku</td>
		<td>tni_nrp</td>
		<td>tni_keanggotaan</td>
		<td>tni_pangkat</td>
		<td>tni_kotama</td>
		<td>tni_satker</td>
		<td>tni_korps</td>
		<td>tni_jabatan</td>
		<td>kerabat_nama</td>
		<td>kerabat_jk</td>
		<td>kerabat_alamat</td>
		<td>kerabat_telp</td>
		<td>kerabat_hubungan</td>
		<td>kerabat_tni_nama</td>
		<td>kerabat_tni_nrp</td>
		<td>kerabat_tni_keanggotaan</td>
		<td>kerabat_tni_pangkat</td>
		<td>kerabat_tni_kotama</td>
		<td>kerabat_tni_satker</td>
		<td>kerabat_hubungan</td>
		@for($i=1;$i<=$max_pembayaran;$i++)
		<td>asuransi_nama_{{$i}}</td>
		<td>asuransi_nomor_{{$i}}</td>
		<td>asuransi_kelas_{{$i}}</td>
		@endfor
	</tr>
	@foreach($pasien as $px)
	<tr>
		<td>{{$px->id}}</td>
		<td>{{$px->no_rm}}</td>
		<td>{{$px->name}}</td>
		<td>{{$px->jk->kode}}</td>
		<td>{{$px->jenis_identitas->nama}}</td>
		<td>{{$px->no_identitas}}</td>
		<td>{{$px->pernikahan->nama}}</td>
		<td>{{$px->place_of_birth}}</td>
		<td>{{$px->date_of_birth}}</td>
		<td>{{$px->address}}</td>
		<td>{{$px->alamat_kota->nama}}</td>
		<td>{{$px->alamat_kecamatan->nama}}</td>
		<td>{{$px->alamat_kelurahan->nama}}</td>
		<td>{{$px->phone}}</td>
		<td>{{$px->job}}</td>
		<td>{{$px->agama->nama}}</td>
		<td>{{$px->pendidikan->nama}}</td>
		<td>{{$px->bahasa}}</td>
		<td>{{$px->suku}}</td>
		<td>{{$px->tni_nrp}}</td>
		<td>{{$px->tni_keanggotaan->nama}}</td>
		<td>{{$px->tni_pangkat->nama}}</td>
		<td>{{$px->tni_kotama->nama}}</td>
		<td>{{$px->tni_satker->nama}}</td>
		<td>{{$px->tni_korps->nama}}</td>
		<td>{{$px->tni_jabatan}}</td>

		<td>{{$px->wali->name}}</td>
		<td>{{$px->wali->jk->kode}}</td>
		<td>{{$px->wali->address}}</td>
		<td>{{$px->wali->phone}}</td>
		<td>{{$px->jenis_hubungan_keluarga->nama}}</td>
		<td>{{$px->wali->tni_nama}}</td>
		<td>{{$px->wali->tni_nrp}}</td>
		<td>{{$px->wali->tni_keanggotaan->nama}}</td>
		<td>{{$px->wali->tni_pangkat->nama}}</td>
		<td>{{$px->wali->tni_kotama->nama}}</td>
		<td>{{$px->wali->tni_satker->nama}}</td>
		<td>{{$px->wali->tni_hubungan->nama}}</td>

		@foreach($px->pembayaran as $pembayaran)
		<td>{{$pembayaran->perusahaan->nama}}</td>
		<td>{{$pembayaran->no_asuransi}}</td>
		<td>{{$pembayaran->kelas->nama}}</td>
		@endforeach
	</tr>
	@endforeach
</table>