
	$(`:radio[name="agama_pasien"][value="${item.agama_pasien}"]`).prop("checked", true);
	$(`:checkbox[name="keyakinan_pasien_pantangan_pemeriksaan_hari_tertentu"]`).prop("checked", item.keyakinan_pasien_pantangan_pemeriksaan_hari_tertentu != null);
	$(`:checkbox[name="keyakinan_pasien_pantangan_masuk_keluar_rs_hari_tertentu"]`).prop("checked", item.keyakinan_pasien_pantangan_masuk_keluar_rs_hari_tertentu != null);
	$(`:checkbox[name="keyakinan_pasien_hanya_ingin_dilayani_sesama_jenis"]`).prop("checked", item.keyakinan_pasien_hanya_ingin_dilayani_sesama_jenis != null);
	$(`:checkbox[name="keyakinan_pasien_pantangan_nomor_tertentu_yang_dihindari"]`).prop("checked", item.keyakinan_pasien_pantangan_nomor_tertentu_yang_dihindari != null);
	$(`:text[name="keterangan_untuk_nilai_dan_keyakinan_pasien"]`).val(item.keterangan_untuk_nilai_dan_keyakinan_pasien);
	$(`:checkbox[name="pendidikan_pasien_sd"]`).prop("checked", item.pendidikan_pasien_sd != null);
	$(`:checkbox[name="pendidikan_pasien_smp"]`).prop("checked", item.pendidikan_pasien_smp != null);
	$(`:checkbox[name="pendidikan_pasien_sma"]`).prop("checked", item.pendidikan_pasien_sma != null);
	$(`:checkbox[name="pendidikan_pasien_perguruan_tinggi"]`).prop("checked", item.pendidikan_pasien_perguruan_tinggi != null);
	$(`:checkbox[name="pendidikan_pasien_tidak_sekolah"]`).prop("checked", item.pendidikan_pasien_tidak_sekolah != null);
	$(`:checkbox[name="pendidikan_pasien_lain_lain"]`).prop("checked", item.pendidikan_pasien_lain_lain != null);
	$(`:checkbox[name="bahasa_yang_digunakan_pasien_indonesia"]`).prop("checked", item.bahasa_yang_digunakan_pasien_indonesia != null);
	$(`:checkbox[name="bahasa_yang_digunakan_pasien_isyarat"]`).prop("checked", item.bahasa_yang_digunakan_pasien_isyarat != null);
	$(`:checkbox[name="bahasa_yang_digunakan_pasien_lain_lain"]`).prop("checked", item.bahasa_yang_digunakan_pasien_lain_lain != null);
	$(`:checkbox[name="keterbatasan_pasien_tuli"]`).prop("checked", item.keterbatasan_pasien_tuli != null);
	$(`:checkbox[name="keterbatasan_pasien_bisu"]`).prop("checked", item.keterbatasan_pasien_bisu != null);
	$(`:checkbox[name="keterbatasan_pasien_kooperatif"]`).prop("checked", item.keterbatasan_pasien_kooperatif != null);
	$(`:checkbox[name="keterbatasan_pasien_perlu_kursi_roda"]`).prop("checked", item.keterbatasan_pasien_perlu_kursi_roda != null);
	$(`:checkbox[name="keterbatasan_pasien_hidup_dalam_pikirannya_sendiri"]`).prop("checked", item.keterbatasan_pasien_hidup_dalam_pikirannya_sendiri != null);
	$(`:checkbox[name="keterbatasan_pasien_tidak_ada_keterbatasan_fisik"]`).prop("checked", item.keterbatasan_pasien_tidak_ada_keterbatasan_fisik != null);
	$(`:checkbox[name="keterbatasan_pasien_tampak_mutualisme_atau_negativistic"]`).prop("checked", item.keterbatasan_pasien_tampak_mutualisme_atau_negativistic != null);
	$(`:checkbox[name="keterbatasan_pasien_mampu_berdiskusi"]`).prop("checked", item.keterbatasan_pasien_mampu_berdiskusi != null);
	$(`:checkbox[name="emosi_motivasi_pasien_tenang"]`).prop("checked", item.emosi_motivasi_pasien_tenang != null);
	$(`:checkbox[name="emosi_motivasi_pasien_labil"]`).prop("checked", item.emosi_motivasi_pasien_labil != null);
	$(`:checkbox[name="emosi_motivasi_pasien_tampak_acuh"]`).prop("checked", item.emosi_motivasi_pasien_tampak_acuh != null);
	$(`:checkbox[name="emosi_motivasi_pasien_belum_mampu_diajak_komunikasi"]`).prop("checked", item.emosi_motivasi_pasien_belum_mampu_diajak_komunikasi != null);
	$(`:checkbox[name="emosi_motivasi_pasien_tampak_agresif"]`).prop("checked", item.emosi_motivasi_pasien_tampak_agresif != null);
	$(`:checkbox[name="emosi_motivasi_pasien_mampu_komunikasi"]`).prop("checked", item.emosi_motivasi_pasien_mampu_komunikasi != null);
	$(`:checkbox[name="kesediaan_pasien_bersedia_diberi_informasi"]`).prop("checked", item.kesediaan_pasien_bersedia_diberi_informasi != null);
	$(`:checkbox[name="kesediaan_pasien_mampu_menerima_informasi"]`).prop("checked", item.kesediaan_pasien_mampu_menerima_informasi != null);
	$(`:checkbox[name="kesediaan_pasien_belum_mampu_menerima_informasi"]`).prop("checked", item.kesediaan_pasien_belum_mampu_menerima_informasi != null);
	$(`:checkbox[name="kesediaan_pasien_tidak_bersedia_diberi_informasi"]`).prop("checked", item.kesediaan_pasien_tidak_bersedia_diberi_informasi != null);
	$(`:text[name="hubungan_dengan_pasien"]`).val(item.hubungan_dengan_pasien);
	$(`:checkbox[name="keyakinan_keluarga_pantangan_pemeriksaan_hari_tertentu"]`).prop("checked", item.keyakinan_keluarga_pantangan_pemeriksaan_hari_tertentu != null);
	$(`:checkbox[name="keyakinan_keluarga_pantangan_masuk_keluar_rs_hari_tertentu"]`).prop("checked", item.keyakinan_keluarga_pantangan_masuk_keluar_rs_hari_tertentu != null);
	$(`:checkbox[name="keyakinan_keluarga_hanya_ingin_dilayani_sesama_jenis"]`).prop("checked", item.keyakinan_keluarga_hanya_ingin_dilayani_sesama_jenis != null);
	$(`:checkbox[name="keyakinan_keluarga_pantangan_nomor_tertentu_yang_dihindari"]`).prop("checked", item.keyakinan_keluarga_pantangan_nomor_tertentu_yang_dihindari != null);
	$(`:text[name="keterangan_untuk_nilai_dan_keyakinan_keluarga"]`).val(item.keterangan_untuk_nilai_dan_keyakinan_keluarga);
	$(`:checkbox[name="pendidikan_keluarga_sd"]`).prop("checked", item.pendidikan_keluarga_sd != null);
	$(`:checkbox[name="pendidikan_keluarga_smp"]`).prop("checked", item.pendidikan_keluarga_smp != null);
	$(`:checkbox[name="pendidikan_keluarga_sma"]`).prop("checked", item.pendidikan_keluarga_sma != null);
	$(`:checkbox[name="pendidikan_keluarga_perguruan_tinggi"]`).prop("checked", item.pendidikan_keluarga_perguruan_tinggi != null);
	$(`:checkbox[name="pendidikan_keluarga_tidak_sekolah"]`).prop("checked", item.pendidikan_keluarga_tidak_sekolah != null);
	$(`:checkbox[name="pendidikan_keluarga_lain_lain"]`).prop("checked", item.pendidikan_keluarga_lain_lain != null);
	$(`:checkbox[name="bahasa_keluarga_indonesia"]`).prop("checked", item.bahasa_keluarga_indonesia != null);
	$(`:checkbox[name="bahasa_keluarga_isyarat"]`).prop("checked", item.bahasa_keluarga_isyarat != null);
	$(`:checkbox[name="bahasa_keluarga_lain_lain"]`).prop("checked", item.bahasa_keluarga_lain_lain != null);
	$(`:checkbox[name="keterbatasan_keluarga_tuli"]`).prop("checked", item.keterbatasan_keluarga_tuli != null);
	$(`:checkbox[name="keterbatasan_keluarga_bisu"]`).prop("checked", item.keterbatasan_keluarga_bisu != null);
	$(`:checkbox[name="keterbatasan_keluarga_kooperatif"]`).prop("checked", item.keterbatasan_keluarga_kooperatif != null);
	$(`:checkbox[name="keterbatasan_keluarga_perlu_kursi_roda"]`).prop("checked", item.keterbatasan_keluarga_perlu_kursi_roda != null);
	$(`:checkbox[name="keterbatasan_keluarga_tidak_ada_keterbatasan_fisik"]`).prop("checked", item.keterbatasan_keluarga_tidak_ada_keterbatasan_fisik != null);
	$(`:checkbox[name="keterbatasan_keluarga_mampu_berdiskusi"]`).prop("checked", item.keterbatasan_keluarga_mampu_berdiskusi != null);
	$(`:checkbox[name="keterbatasan_keluarga_lain_lain"]`).prop("checked", item.keterbatasan_keluarga_lain_lain != null);
	$(`:checkbox[name="emosi_motivasi_keluarga_tenang"]`).prop("checked", item.emosi_motivasi_keluarga_tenang != null);
	$(`:checkbox[name="emosi_motivasi_keluarga_labil"]`).prop("checked", item.emosi_motivasi_keluarga_labil != null);
	$(`:checkbox[name="emosi_motivasi_keluarga_tampak_acuh"]`).prop("checked", item.emosi_motivasi_keluarga_tampak_acuh != null);
	$(`:checkbox[name="emosi_motivasi_keluarga_belum_mampu_diajak_komunikasi"]`).prop("checked", item.emosi_motivasi_keluarga_belum_mampu_diajak_komunikasi != null);
	$(`:checkbox[name="emosi_motivasi_keluarga_mampu_komunikasi"]`).prop("checked", item.emosi_motivasi_keluarga_mampu_komunikasi != null);
	$(`:checkbox[name="kesediaan_keluarga_bersedia_diberi_informasi"]`).prop("checked", item.kesediaan_keluarga_bersedia_diberi_informasi != null);
	$(`:checkbox[name="kesediaan_keluarga_mampu_menerima_informasi"]`).prop("checked", item.kesediaan_keluarga_mampu_menerima_informasi != null);
	$(`:checkbox[name="kesediaan_keluarga_tidak_bersedia_diberi_informasi"]`).prop("checked", item.kesediaan_keluarga_tidak_bersedia_diberi_informasi != null);
	$(`:checkbox[name="edukasi_pasien_penyakit_yang_diderita"]`).prop("checked", item.edukasi_pasien_penyakit_yang_diderita != null);
	$(`:checkbox[name="edukasi_pasien_teknik_rehabilitasi_terapi_kerja_latihan_asertif"]`).prop("checked", item.edukasi_pasien_teknik_rehabilitasi_terapi_kerja_latihan_asertif != null);
	$(`:checkbox[name="edukasi_pasien_tindakan_keperawatan_fiksasi_tak_dll"]`).prop("checked", item.edukasi_pasien_tindakan_keperawatan_fiksasi_tak_dll != null);
	$(`:checkbox[name="edukasi_pasien_tindakan_medis_ect_konvensional_dll"]`).prop("checked", item.edukasi_pasien_tindakan_medis_ect_konvensional_dll != null);
	$(`:checkbox[name="edukasi_pasien_pemeriksaan_penunjang_lab_rontgen_dll"]`).prop("checked", item.edukasi_pasien_pemeriksaan_penunjang_lab_rontgen_dll != null);
	$(`:text[name="masalah_keperawatan"]`).val(item.masalah_keperawatan);
	$(`:text[name="rencana_edukasi_pasien_tanggal"]`).val(formatDate(item.rencana_edukasi_pasien_tanggal));
	$(`:checkbox[name="kebutuhan_edukasi_keluarga_obat_yang_dikonsumsi"]`).prop("checked", item.kebutuhan_edukasi_keluarga_obat_yang_dikonsumsi != null);
	$(`:checkbox[name="kebutuhan_edukasi_keluarga_managemen_nyeri"]`).prop("checked", item.kebutuhan_edukasi_keluarga_managemen_nyeri != null);
	$(`:checkbox[name="kebutuhan_edukasi_keluarga_diet_dan_nutrisi"]`).prop("checked", item.kebutuhan_edukasi_keluarga_diet_dan_nutrisi != null);
	$(`:checkbox[name="kebutuhan_edukasi_keluarga_cuci_tangan"]`).prop("checked", item.kebutuhan_edukasi_keluarga_cuci_tangan != null);
	$(`:checkbox[name="kebutuhan_edukasi_keluarga_inform_consent"]`).prop("checked", item.kebutuhan_edukasi_keluarga_inform_consent != null);
	$(`:checkbox[name="kebutuhan_edukasi_keluarga_general_consent"]`).prop("checked", item.kebutuhan_edukasi_keluarga_general_consent != null);
	$(`:text[name="rencana_edukasi_keluarga_tanggal"]`).val(formatDate(item.rencana_edukasi_keluarga_tanggal));
	$(`:radio[name="agama_keluarga_pasien"][value="${item.agama_keluarga_pasien}"]`).prop("checked", true);