
	$(`:text[name="tanggal_transfer"]`).val(formatDate(item.tanggal_transfer));
	$(`:text[name="alergi_obat"]`).val(item.alergi_obat);
	$(`:text[name="ruangan_asal"]`).val(item.ruangan_asal);
	$(`:text[name="nama_perawat_pengirim"]`).val(item.nama_perawat_pengirim);
	$(`:text[name="jam_berangkat_dari_ruangan"]`).val(item.jam_berangkat_dari_ruangan);
	$(`:text[name="tekanan_darah_1"]`).val(item.tekanan_darah_1);
	$(`:text[name="nadi_1"]`).val(item.nadi_1);
	$(`:text[name="suhu_1"]`).val(item.suhu_1);
	$(`:text[name="respirasi_1"]`).val(item.respirasi_1);
	$(`:text[name="gcs_e_1"]`).val(item.gcs_e_1);
	$(`:text[name="gcs_v_1"]`).val(item.gcs_v_1);
	$(`:text[name="gcs_m_1"]`).val(item.gcs_m_1);
	$(`:radio[name="gelisah_1"][value="${item.gelisah_1}"]`).prop("checked", true);
	$(`:radio[name="agresif_1"][value="${item.agresif_1}"]`).prop("checked", true);
	$(`:radio[name="fiksasi_1"][value="${item.fiksasi_1}"]`).prop("checked", true);
	$(`:radio[name="korban_pasung_1"][value="${item.korban_pasung_1}"]`).prop("checked", true);
	$(`:radio[name="indikasi_bunuh_diri_1"][value="${item.indikasi_bunuh_diri_1}"]`).prop("checked", true);
	$(`:radio[name="indikasi_jatuh_1"][value="${item.indikasi_jatuh_1}"]`).prop("checked", true);
	$(`:radio[name="skala_nyeri_1"][value="${item.skala_nyeri_1}"]`).prop("checked", true);
	$(`:text[name="ruangan_tujuan"]`).val(item.ruangan_tujuan);
	$(`:text[name="nama_perawat_penerima"]`).val(item.nama_perawat_penerima);
	$(`:text[name="jam_tiba_di_ruangan"]`).val(item.jam_tiba_di_ruangan);
	$(`:text[name="tekanan_darah_2"]`).val(item.tekanan_darah_2);
	$(`:text[name="nadi_2"]`).val(item.nadi_2);
	$(`:text[name="suhu_2"]`).val(item.suhu_2);
	$(`:text[name="respirasi_2"]`).val(item.respirasi_2);
	$(`:text[name="gcs_e_2"]`).val(item.gcs_e_2);
	$(`:text[name="gcs_v_2"]`).val(item.gcs_v_2);
	$(`:text[name="gcs_m_2"]`).val(item.gcs_m_2);
	$(`:text[name="keterangan_radiologi"]`).val(item.keterangan_radiologi);
	$(`:text[name="keterangan_laborat"]`).val(item.keterangan_laborat);
	$(`:text[name="keterangan_ekg"]`).val(item.keterangan_ekg);
	$(`:text[name="keterangan_eeg"]`).val(item.keterangan_eeg);
	$(`:radio[name="gelisah_2"][value="${item.gelisah_2}"]`).prop("checked", true);
	$(`:radio[name="agresif_2"][value="${item.agresif_2}"]`).prop("checked", true);
	$(`:radio[name="fiksasi_2"][value="${item.fiksasi_2}"]`).prop("checked", true);
	$(`:radio[name="korban_pasung_2"][value="${item.korban_pasung_2}"]`).prop("checked", true);
	$(`:radio[name="indikasi_bunuh_diri_2"][value="${item.indikasi_bunuh_diri_2}"]`).prop("checked", true);
	$(`:radio[name="indikasi_jatuh_2"][value="${item.indikasi_jatuh_2}"]`).prop("checked", true);
	$(`:radio[name="skala_nyeri_2"][value="${item.skala_nyeri_2}"]`).prop("checked", true);
	$(`textarea[name="keterangan_khusus"]`).val(item.keterangan_khusus);
	$(`:checkbox[name="pemeriksaan_radiologi"]`).prop("checked", item.pemeriksaan_radiologi != null);
	$(`:checkbox[name="pemeriksaan_laborat"]`).prop("checked", item.pemeriksaan_laborat != null);
	$(`:checkbox[name="pemeriksaan_ekg"]`).prop("checked", item.pemeriksaan_ekg != null);
	$(`:checkbox[name="pemeriksaan_eeg_bm"]`).prop("checked", item.pemeriksaan_eeg_bm != null);
	$(`:checkbox[name="hasil_pemeriksaan_keluar_radiologi"]`).prop("checked", item.hasil_pemeriksaan_keluar_radiologi != null);
	$(`:checkbox[name="hasil_pemeriksaan_keluar_laborat"]`).prop("checked", item.hasil_pemeriksaan_keluar_laborat != null);
	$(`:checkbox[name="hasil_pemeriksaan_keluar_ekg"]`).prop("checked", item.hasil_pemeriksaan_keluar_ekg != null);
	$(`:checkbox[name="hasil_pemeriksaan_keluar_eeg_bm"]`).prop("checked", item.hasil_pemeriksaan_keluar_eeg_bm != null);
	$(`textarea[name="obat_yang_dibawa"]`).val(item.obat_yang_dibawa);