$(`:text[name="ruangan_tujuan"]`).val(item.ruangan_tujuan);
$(`:text[name="nama_perawat_penerima"]`).val(item.nama_perawat_penerima);
$(`:text[name="jam_tiba_di_ruangan"]`).val(item.jam_tiba_di_ruangan);
$(`:text[name="tekanan_darah_2"]`).val(item.tekanan_darah_2);
$(`:text[name="nadi_2"]`).val(item.nadi_2);
$(`:text[name="suhu_2"]`).val(item.suhu_2);
$(`:text[name="respirasi_2"]`).val(item.respirasi_2);
$(`:text[name="gcs_e_2"]`).val(item.gcs_e_2);
$(`:text[name="gcs_v_2"]`).val(item.gcs_v_2);
$(`:text[name="gcs_m_2"]`).val(item.gcs_m_2);
$(`:text[name="keterangan_radiologi"]`).val(item.keterangan_radiologi);
$(`:text[name="keterangan_laborat"]`).val(item.keterangan_laborat);
$(`:text[name="keterangan_ekg"]`).val(item.keterangan_ekg);
$(`:text[name="keterangan_eeg"]`).val(item.keterangan_eeg);
$(`:radio[name="gelisah_2"][value="${item.gelisah_2}"]`).prop("checked", true);
$(`:radio[name="agresif_2"][value="${item.agresif_2}"]`).prop("checked", true);
$(`:radio[name="fiksasi_2"][value="${item.fiksasi_2}"]`).prop("checked", true);
$(`:radio[name="korban_pasung_2"][value="${item.korban_pasung_2}"]`).prop("checked", true);
$(`:radio[name="indikasi_bunuh_diri_2"][value="${item.indikasi_bunuh_diri_2}"]`).prop("checked", true);
$(`:radio[name="indikasi_jatuh_2"][value="${item.indikasi_jatuh_2}"]`).prop("checked", true);
$(`:radio[name="skala_nyeri_2"][value="${item.skala_nyeri_2}"]`).prop("checked", true);