
	$(`:text[name="alasan_pengiriman"]`).val(item.alasan_pengiriman);
	$(`:radio[name="bisa_bekerja_sama"][value="${item.bisa_bekerja_sama}"]`).prop("checked", true);
	$(`:radio[name="aktif"][value="${item.aktif}"]`).prop("checked", true);
	$(`:radio[name="sikap_tenang"][value="${item.sikap_tenang}"]`).prop("checked", true);
	$(`:radio[name="mudah_menjawab"][value="${item.mudah_menjawab}"]`).prop("checked", true);
	$(`:radio[name="yakin"][value="${item.yakin}"]`).prop("checked", true);
	$(`:radio[name="kritis"][value="${item.kritis}"]`).prop("checked", true);
	$(`:radio[name="cepat"][value="${item.cepat}"]`).prop("checked", true);
	$(`:radio[name="hati_hati"][value="${item.hati_hati}"]`).prop("checked", true);
	$(`:radio[name="berpikir_cepat"][value="${item.berpikir_cepat}"]`).prop("checked", true);
	$(`:radio[name="rapi"][value="${item.rapi}"]`).prop("checked", true);
	$(`:radio[name="perilaku_tenang"][value="${item.perilaku_tenang}"]`).prop("checked", true);
	$(`:radio[name="mengetahui"][value="${item.mengetahui}"]`).prop("checked", true);
	$(`:radio[name="bekerja_keras"][value="${item.bekerja_keras}"]`).prop("checked", true);
	$(`:radio[name="reaksi_gagal_tenang"][value="${item.reaksi_gagal_tenang}"]`).prop("checked", true);
	$(`:radio[name="reaksi_tenang"][value="${item.reaksi_tenang}"]`).prop("checked", true);
	$(`:radio[name="semakin_giat"][value="${item.semakin_giat}"]`).prop("checked", true);
	$(`:radio[name="cara_bicara_baik"][value="${item.cara_bicara_baik}"]`).prop("checked", true);
	$(`:radio[name="jawaban_jelas"][value="${item.jawaban_jelas}"]`).prop("checked", true);
	$(`:radio[name="spontan"][value="${item.spontan}"]`).prop("checked", true);
	$(`:radio[name="reaksi_cepat"][value="${item.reaksi_cepat}"]`).prop("checked", true);
	$(`:radio[name="coba_coba"][value="${item.coba_coba}"]`).prop("checked", true);
	$(`:radio[name="gerakan_baik"][value="${item.gerakan_baik}"]`).prop("checked", true);
	$(`:radio[name="koordinasi_baik"][value="${item.koordinasi_baik}"]`).prop("checked", true);
	$(`:text[name="intelegensi_umum"]`).val(item.intelegensi_umum);
	$(`:radio[name="pengertian_umum"][value="${item.pengertian_umum}"]`).prop("checked", true);
	$(`:radio[name="kemampuan_visual_motor"][value="${item.kemampuan_visual_motor}"]`).prop("checked", true);
	$(`:radio[name="kemampuan_berhitung"][value="${item.kemampuan_berhitung}"]`).prop("checked", true);
	$(`:radio[name="kemampuan_mengingat_dan_berkonsentrasi"][value="${item.kemampuan_mengingat_dan_berkonsentrasi}"]`).prop("checked", true);
	$(`:radio[name="perbendaharaan_kata"][value="${item.perbendaharaan_kata}"]`).prop("checked", true);
	$(`:radio[name="pemahaman_dan_penalaran"][value="${item.pemahaman_dan_penalaran}"]`).prop("checked", true);
	$(`textarea[name="ringkasan_dan_saran"]`).val(item.ringkasan_dan_saran);
	$(`textarea[name="catatan"]`).val(item.catatan);