
	$(`:text[name="tanggal_pemeriksaan"]`).val(formatDate(item.tanggal_pemeriksaan));
    $(`:text[name="tujuan_tes"]`).val(item.tujuan_tes);
	$(`:radio[name="kerja_sama"][value="${item.kerja_sama}"]`).prop("checked", true);
	$(`:radio[name="tester_pasif_aktif"][value="${item.tester_pasif_aktif}"]`).prop("checked", true);
	$(`:radio[name="tester_tegang_tenang"][value="${item.tester_tegang_tenang}"]`).prop("checked", true);
	$(`:radio[name="tester_menjawab"][value="${item.tester_menjawab}"]`).prop("checked", true);
	$(`:radio[name="sikap_keyakinan"][value="${item.sikap_keyakinan}"]`).prop("checked", true);
	$(`:radio[name="sikap_penerimaan"][value="${item.sikap_penerimaan}"]`).prop("checked", true);
	$(`:radio[name="kecepatan_kerja"][value="${item.kecepatan_kerja}"]`).prop("checked", true);
	$(`:radio[name="kecekatan_kerja"][value="${item.kecekatan_kerja}"]`).prop("checked", true);
	$(`:radio[name="pikiran_kerja"][value="${item.pikiran_kerja}"]`).prop("checked", true);
	$(`:radio[name="kerapian_kerja"][value="${item.kerapian_kerja}"]`).prop("checked", true);
	$(`:radio[name="perilaku"][value="${item.perilaku}"]`).prop("checked", true);
	$(`:radio[name="pengetahuan_kegagalan"][value="${item.pengetahuan_kegagalan}"]`).prop("checked", true);
	$(`:radio[name="usaha"][value="${item.usaha}"]`).prop("checked", true);
	$(`:radio[name="kondisi_kegagalan"][value="${item.kondisi_kegagalan}"]`).prop("checked", true);
	$(`:radio[name="ketenangan_bicara"][value="${item.ketenangan_bicara}"]`).prop("checked", true);
	$(`:radio[name="reaksi_bicara"][value="${item.reaksi_bicara}"]`).prop("checked", true);
	$(`:radio[name="kondisi_bicara"][value="${item.kondisi_bicara}"]`).prop("checked", true);
	$(`:radio[name="kejelasan_jawaban"][value="${item.kejelasan_jawaban}"]`).prop("checked", true);
	$(`:radio[name="kecakapan_bicara"][value="${item.kecakapan_bicara}"]`).prop("checked", true);
	$(`:radio[name="kecepatan_reaksi"][value="${item.kecepatan_reaksi}"]`).prop("checked", true);
	$(`:radio[name="reaksi_kehati_hatian"][value="${item.reaksi_kehati_hatian}"]`).prop("checked", true);
	$(`:radio[name="reaksi_gerakan"][value="${item.reaksi_gerakan}"]`).prop("checked", true);
	$(`:radio[name="keadaan_koordinasi_motorik"][value="${item.keadaan_koordinasi_motorik}"]`).prop("checked", true);
	$("#kesimpulan").html(item.kesimpulan);
	$("#saran").html(item.saran);
	$("#catatan").html(item.catatan);
	$(`:text[name="kategori"]`).val(item.kategori);
	$(`:radio[name="kecerdasan_umum"][value="${item.kecerdasan_umum}"]`).prop("checked", true);
	$(`:radio[name="pengamatan_ruang"][value="${item.pengamatan_ruang}"]`).prop("checked", true);
	$(`:radio[name="kemampuan_analisa"][value="${item.kemampuan_analisa}"]`).prop("checked", true);
	$(`:radio[name="kemampuan_berpikir_analogi"][value="${item.kemampuan_berpikir_analogi}"]`).prop("checked", true);
	$(`:radio[name="emosi"][value="${item.emosi}"]`).prop("checked", true);
	$(`:radio[name="kemampuan_sosial"][value="${item.kemampuan_sosial}"]`).prop("checked", true);
	$(`:radio[name="kemampuan_adaptasi"][value="${item.kemampuan_adaptasi}"]`).prop("checked", true);
	$(`:radio[name="motivasi_prestasi"][value="${item.motivasi_prestasi}"]`).prop("checked", true);